version: '3.8'

services:

  # InfluxDB
  influxdb:
    image: influxdb:2.7.12
    container_name: influxdb_2.7.12
    restart: always
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: example123
      DOCKER_INFLUXDB_INIT_ORG: research
      DOCKER_INFLUXDB_INIT_BUCKET: research
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: research_token
