version: '3.8'

services:

  # MariaDB
  mariadb:
    image: mariadb:lts-ubi9
    container_name: mariadb_lts-ubi9
    restart: always
    volumes:
      - $PWD/data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: research
