version: '3.8'

services:

  # MySQL
  mysql:
    image: mysql:9.3.0
    container_name: mysql_9.3.0
    restart: always
    volumes:
      - $PWD/data/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: research
