version: '3.8'

services:

  # PostgreSQL
  postgres:
    image: postgres:17.5
    container_name: postgres_17.5
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: research
